//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zed.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyRate
    {
        public int CurrencyID { get; set; }
        public string CurrencyFrom { get; set; }
        public string CurrencyTo { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> RateUpdateTime { get; set; }
    }
}
